### ISSUE TITLE
'build' task no longer 'uglifying' javascript code?

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-grunt#20]
when I 'build' the standard Adapt OS project, JavaScript code is minified using uglify2 - but the same doesn't seem to be happening with our Gruntfile, leading to adapt.min.js frequently being over 1MB - which is a pretty big initial download.

I've had a bit of a look through the Gruntfile and, as far as I can see, the '_build' task seems to use 'buildProcessDev' no matter what you do...

**Comment by tomgreenfield** [comment]
Hi @moloko, have you tried updating your version of node?

This was happening to me at the end of last year so I updated the Gruntfile locally in ken13183, but it looks like the issue has since been fixed because the '_build' task now runs correctly on our clean installs.

**Comment by moloko** [comment]
aha yes, I was just on my way here to say that updating node.js hadn't worked.

I will take a look at that changeset. certainly looks more readable than the - quite frankly mental syntax - of lines like 
```
!!devMode === true
```
I do not not fail to comprehend what that does not mean

**Comment by oliverfoster** [comment]
xD

**Comment by taylortom** [comment]
I have absolutely no idea

**Comment by moloko** [comment]
OK, fixed in develop now.
